name: manual-dispatch
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: environment
      categories:
        description: 'Categories to run'
        required: true
        default: 'Smoke'
        type: string
      rerun:
        description: 'Rerun'
        required: false
        default: false
        type: boolean
jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ inputs.rerun }}
    steps:
      - name: Print the input to STDOUT
        run: echo  The input is ${{ inputs.environment }}
